apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: nfs-csi
    annotations:
      pv.beta.kubernetes.io/gid: "65534"
provisioner: nfs.csi.k8s.io
parameters:
    server: 10.0.0.3
    share: /srv/nfs
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
    - hard
